name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Create venv and install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -e ".[dev]"
    
    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest --cov=pubkit
    
    - name: Check formatting
      run: |
        source .venv/bin/activate
        black . --check
        isort . --check
    
    - name: Type check
      run: |
        source .venv/bin/activate
        mypy src/pubkit 